#ifdef GL_ES
#if defined(GL_FRAGMENT_PRECISION_HIGH) || defined(NANOVG_GL3)
 precision highp float;
#else
 precision mediump float;
#endif
#endif
uniform vec4 renderInfo;
#define fRenderTime renderInfo.x
#ifdef NANOVG_GL3
#ifdef USE_UNIFORMBUFFER
	layout(std140) uniform frag {
		mat3 scissorMat;
		mat3 paintMat;
		vec4 innerCol;
		vec4 outerCol;
		vec2 scissorExt;
		vec2 scissorScale;
		vec2 extent;
		float radius;
		float feather;
		float strokeMult;
		float strokeThr;
		int texType;
		int type;
	};
#else
	uniform vec4 frag[UNIFORMARRAY_SIZE];
#endif
	uniform sampler2D tex;
	in vec2 ftcoord;
	in vec2 fpos;
	out vec4 outColor;
#else
	uniform vec4 frag[UNIFORMARRAY_SIZE];
	uniform sampler2D tex;
	varying vec2 ftcoord;
	varying vec2 fpos;
#endif
#ifndef USE_UNIFORMBUFFER
	#define scissorMat mat3(frag[0].xyz, frag[1].xyz, frag[2].xyz)
	#define paintMat mat3(frag[3].xyz, frag[4].xyz, frag[5].xyz)
	#define innerCol frag[6]
	#define outerCol frag[7]
	#define scissorExt frag[8].xy
	#define scissorScale frag[8].zw
	#define extent frag[9].xy
	#define radius frag[9].z
	#define feather frag[9].w
	#define strokeMult frag[10].x
	#define strokeThr frag[10].y
	#define texType int(frag[10].z)
	#define type int(frag[10].w)
#endif


vec3 palette( in float t, in vec3 a, in vec3 b, in vec3 c, in vec3 d )
{
    return a + b *cos( 6.28318*(c*t+d) );
}
void mainDbgTexc(void) {
   vec4 result;
		// result = vec4(vec3(max(extent.x, extent.y)), 1.0);
		vec2 pt = (paintMat * vec3(fpos,1.0)).xy / (extent);
		result = vec4(pt.xy, 0.0, 1.0);
#ifdef NANOVG_GL3
	outColor = result;
#else
	gl_FragColor = result;
#endif
}

//note: uniformly distributed, normalized rand, [0;1[
float nrand( vec2 n )
{
	return fract(sin(dot(n.xy, vec2(12.9898, 78.233)))* 43758.5453);
}
//note: remaps v to [0;1] in interval [a;b]
float remap( float a, float b, float v )
{
	return clamp( (v-a) / (b-a), 0.0, 1.0 );
}
//note: quantizes in l levels
float trunc_( float a, float l )
{
	return floor(a*l)/l;
}

float n1rand( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = nrand( n + 0.07*t );
	return nrnd0;
}
float n2rand( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = nrand( n + 0.07*t );
	float nrnd1 = nrand( n + 0.11*t );
	return (nrnd0+nrnd1) / 2.0;
}

float n2rand_faster( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = fract(sin(dot(( n + 0.07*t ).xy, vec2(12.9898, 78.233)))* 43758.5453);

    // Convert uniform distribution into triangle-shaped distribution.
    float orig = nrnd0*2.0-1.0;
    nrnd0 = orig*inversesqrt(abs(orig));
    nrnd0 = max(-1.0,nrnd0); // Nerf the NaN generated by 0*rsqrt(0). Thanks @FioraAeterna!
    nrnd0 = nrnd0-sign(orig)+0.5;
    
    // Result is range [-0.5,1.5] which is
    // useful for actual dithering.
    // convert to [0,1] for histogram.
    return (nrnd0+0.5) * 0.5;
}
float n3rand( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = nrand( n + 0.07*t );
	float nrnd1 = nrand( n + 0.11*t );
	float nrnd2 = nrand( n + 0.13*t );
	return (nrnd0+nrnd1+nrnd2) / 3.0;
}
float n4rand( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = nrand( n + 0.07*t );
	float nrnd1 = nrand( n + 0.11*t );	
	float nrnd2 = nrand( n + 0.13*t );
	float nrnd3 = nrand( n + 0.17*t );
	return (nrnd0+nrnd1+nrnd2+nrnd3) / 4.0;
}
float n4rand_inv( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = nrand( n + 0.07*t );
	float nrnd1 = nrand( n + 0.11*t );	
	float nrnd2 = nrand( n + 0.13*t );
	float nrnd3 = nrand( n + 0.17*t );
    float nrnd4 = nrand( n + 0.19*t );
	float v1 = (nrnd0+nrnd1+nrnd2+nrnd3) / 4.0;
    float v2 = 0.5 * remap( 0.0, 0.5, v1 ) + 0.5;
    float v3 = 0.5 * remap( 0.5, 1.0, v1 );
    return (nrnd4<0.5) ? v2 : v3;
}

float aastep(float threshold, float value) {
  #ifdef GL_OES_standard_derivatives
    float afwidth = length(vec2(dFdx(value), dFdy(value))) * 0.70710678118654757;
    return smoothstep(threshold-afwidth, threshold+afwidth, value);
  #else
    return step(threshold, value);
  #endif  
}
float sdroundrect(vec2 pt, vec2 ext, float rad) {
	vec2 ext2 = ext - vec2(rad,rad);
	vec2 d = abs(pt) - ext2;
	return min(max(d.x,d.y),0.0) + length(max(d,0.0)) - rad;
}

// Scissoring
float scissorMask(vec2 p) {
	vec2 sc = (abs((scissorMat * vec3(p,1.0)).xy) - scissorExt);
	sc = vec2(0.5,0.5) - sc * scissorScale;
	// return min(1.0, sc.x*sc.y);
	return clamp(sc.x,0.0,1.0) * clamp(sc.y,0.0,1.0);
}
#ifdef EDGE_AA
// Stroke - from [0..1] to clipped pyramid, where the slope is 1px.
float strokeMask() {
return smoothstep(0.0, 1.0, (1.0-abs(ftcoord.x*2.0-1.0))*strokeMult) * smoothstep(0.0, 1.0, ftcoord.y);
}
#endif

// #define SIMPLE_SHADING
#define COLOR_SHADING

vec4 applyShading(vec2 pt, vec2 texcoord, vec4 color) {
	vec4 result = color;
	float fTimeSeconds = renderInfo.x;
	
	float fPerS = 2.0;
	float fTmProgr = mod(fTimeSeconds+fPerS/2.0, 4);
	/* /\________  1s anim 4s sleep (5s cycle)*/
	float fadeTri = clamp(1.0-abs(fTmProgr*2.0/fPerS-1.0), 0.0, 1.0);
	fadeTri = pow(fadeTri, 2);
	float speed = 0.3+pow(fTmProgr/fPerS, 8.0)*20.0;
	float normalizedNoise = n3rand( pt.xy );
	float antiBandingDither = (-0.5+2.0*normalizedNoise)/256.0; // for 8 bit output
	float highlightShade = 0.0 + fadeTri;
#ifdef COLOR_SHADING
	//noninverse
	// vec2 txF = clamp(pow(abs((texcoord*2.0)-1.0), vec2(2.0)), 0.0, 1.0);
	//inverse is also nice

	// vec2 txF = clamp(1.0-pow(abs((texcoord*2.0)-1.0), vec2(8.0)), 0.0, 1.0);

	vec2 Border = 0.5 + 0.5*sqrt(4.0*texcoord*(1.0-texcoord));
	float fPal = Border.y*Border.y;
	float fFade = Border.x*Border.y*Border.x*Border.y*Border.x*Border.y;
	vec3 paletteColor = palette( Border.y*Border.y, vec3(0.5,0.5,0.5),vec3(0.5,0.5,0.5),vec3(1.0,1.0,1.0),vec3(0.0,0.10,0.20) );
	// result.rgb=mix(result.rgb, result.rgb*paletteColor.x, 0*fFade);
	result.rgb=mix(result.rgb, paletteColor.rgb, 0.04*fFade)*1.2;
	{
		
		vec2 txF = clamp(1.0-pow(abs((texcoord*2.0)-1.0), vec2(8.0)), 0.0, 1.0);
		float f = txF.x*txF.y;//clamp(dot(Border, Border), 0.0, 1.0);
		float pal2Idx = 1-f;
		vec3 paletteColor2 = palette( pal2Idx+fTmProgr, vec3(0.5,0.5,0.5),vec3(0.5,0.5,0.5),vec3(1.0,1.0,1.0),vec3(0.3,0.20,0.20) );
		result.rgb=mix(result.rgb, paletteColor2, 0.13*highlightShade);
	}
	result.rgb+=vec3(antiBandingDither);
#endif
	// result.rgb = mix(result.rgb, paletteColor, intens*1);
#ifdef SIMPLE_SHADING
	vec2 Border = 0.5 + 0.5*sqrt(4.0*texcoord*(1.0-texcoord));
	Border = pow(Border, vec2(2.0));
	float f = dot(Border, Border);
	result.rgb*=vec3(mix(f, 1, 0.9));
	result.rgb+=vec3(antiBandingDither);
#endif
	return result;
	// return clamp(result, vec4(0.0), vec4(1.0));
}
void main(void) {
	float scissor = scissorMask(fpos);
	vec4 result = vec4(0,0,0,1);
	vec2 fragTexCoord = vec2(0);
#ifdef EDGE_AA
	float strokeAlpha = strokeMask();
	if (strokeAlpha < strokeThr) discard;
#else
	float strokeAlpha = 1.0;
#endif
#define SHADE_NANOVG
#ifdef SHADE_NANOVG
	//yaaa lousy branch in shader
	if (type == 0) {                        // Gradient
		// Calculate gradient color using box gradient
		vec2 pt = (paintMat * vec3(fpos,1.0)).xy;
		vec2 texcoord = pt / extent;
		fragTexCoord = texcoord;
		float d = clamp((sdroundrect(pt, extent, radius) + feather*0.5) / feather, 0.0, 1.0);
		vec4 color = mix(innerCol,outerCol,d);
		// Combine alpha
		float mask = strokeAlpha * scissor;
		vec4 shadedColor;
		if (abs(extent.x)+abs(extent.y) > 0) {
			shadedColor = applyShading(pt, texcoord, color);
		} else {
			shadedColor = color;
		}
		result = shadedColor * strokeAlpha * scissor;
	} else if (type == 1) {         // Image
		// Calculate color fron texture
		vec2 pt = (paintMat * vec3(fpos,1.0)).xy / extent;
		fragTexCoord = pt;
#ifdef NANOVG_GL3
		vec4 color = texture(tex, pt);
#else
		vec4 color = texture2D(tex, pt);
#endif
		if (texType == 1) 
			color = vec4(color.xyz*color.w,color.w);
		if (texType == 2) 
			color = vec4(color.x);                // Apply color tint and alpha.
		result = color * innerCol * strokeAlpha * scissor;
#if 0
		result = vec4(0,0,0,1);
		result.y = texture(tex, pt).y;
#endif
	} else if (type == 2) {         // Stencil fill
		result = vec4(1,1,1,1);
	} else if (type == 3) {         // Textured tris
		fragTexCoord = ftcoord;
#ifdef NANOVG_GL3
		vec4 color = texture(tex, ftcoord);
#else
		vec4 color = texture2D(tex, ftcoord);
#endif
		if (texType == 1) 
			color = vec4(color.xyz*color.w,color.w);
		if (texType == 2) 
			color = vec4(color.x);       
		result = color * innerCol * scissor;
	} else if (type == 4) {         // colored tri
		fragTexCoord = ftcoord;
		// 0 flat
		// 1 shaded
		// 2 aa vertical lines
		vec4 color = vec4(0.0);
		if (texType == 1) {
			color = applyShading(fpos.xy, ftcoord.xy, innerCol);
		} else if (texType == 2) {
			float distCenterX = (abs(0.5 - ftcoord.x) * 4.) * feather;
			float intens = clamp(1.0 - distCenterX, 0., 1.);
			color = innerCol * intens;
		} else {
			color = innerCol;
		}
		result = color * scissor;
	} else if (type == 5) {         // opengl renders rect that fragment shader turns into circle
		fragTexCoord = ftcoord;
		vec2 distCenter = abs((ftcoord-vec2(0.5))*2.0);
		float intens = 1.0f-aastep(0.9, length(distCenter));
		vec2 Border = 0.5 + 0.5*sqrt(4.0*ftcoord*(1.0-ftcoord));
		result = innerCol*scissor;
		result *= Border.y*Border.x*intens;
	}
#endif
#if 1
	// vec4 colorDbg = vec4(fragTexCoord.xy, 1.0, 1.0);
	// {
			
	// 	float fTimeSeconds = renderInfo.x;
		
	// 	float fPerS = 1.0;
	// 	float fTmProgr = mod(fTimeSeconds+fPerS/2.0, 4);
	// 	/* /\________  1s anim 4s sleep (5s cycle)*/
	// 	float fadeTri = clamp(1.0-abs(fTmProgr*2.0/fPerS-1.0), 0.0, 1.0);
	// 	if (result.r < 0 || result.g < 0 || result.b < 0 || result.a < 0) {
	// 		result = vec4(1, 0, 0, 1);
	// 	} else {
	// 	}
	// }
	// result = result*0.5+0.5*vec4(fragTexCoord.xy, 1.0, 1.0);
#else
#endif
	if (result.a < 1.0/2048.0) 
		discard;
#ifdef NANOVG_GL3
	outColor = result;
#else
	gl_FragColor = result;
#endif
}