#ifdef GL_ES
#if defined(GL_FRAGMENT_PRECISION_HIGH) || defined(NANOVG_GL3)
 precision highp float;
#else
 precision mediump float;
#endif
#endif
uniform vec4 renderInfo;
#define fRenderTime renderInfo.x
#ifdef NANOVG_GL3
#ifdef USE_UNIFORMBUFFER
	layout(std140) uniform frag {
		mat3 scissorMat;
		mat3 paintMat;
		vec4 innerCol;
		vec4 outerCol;
		vec2 scissorExt;
		vec2 scissorScale;
		vec2 extent;
		float strokeMult;
		float strokeThr;
		int texType;
		int type;
	};
#else
	uniform vec4 frag[UNIFORMARRAY_SIZE];
#endif
	uniform sampler2D tex;
	in vec2 ftcoord;
	in vec2 fpos;
	out vec4 outColor;
#else
	uniform vec4 frag[UNIFORMARRAY_SIZE];
	uniform sampler2D tex;
	varying vec2 ftcoord;
	varying vec2 fpos;
#endif
#ifndef USE_UNIFORMBUFFER
	#define scissorMat mat3(frag[0].xyz, frag[1].xyz, frag[2].xyz)
	#define paintMat mat3(frag[3].xyz, frag[4].xyz, frag[5].xyz)
	#define innerCol frag[6]
	#define outerCol frag[7]
	#define scissorExt frag[8].xy
	#define scissorScale frag[8].zw
	#define extent frag[9].xy
	#define strokeMult frag[9].z
	#define strokeThr frag[9].w
	#define texType int(frag[10].x)
	#define type int(frag[10].y)
#endif


vec3 palette( in float t, in vec3 a, in vec3 b, in vec3 c, in vec3 d )
{
    return a + b *cos( 6.28318*(c*t+d) );
}
void mainDbgTexc(void) {
   vec4 result;
		// result = vec4(vec3(max(extent.x, extent.y)), 1.0);
		vec2 pt = (paintMat * vec3(fpos,1.0)).xy / (extent);
		result = vec4(pt.xy, 0.0, 1.0);
#ifdef NANOVG_GL3
	outColor = result;
#else
	gl_FragColor = result;
#endif
}

//note: uniformly distributed, normalized rand, [0;1[
float nrand( vec2 n )
{
	return fract(sin(dot(n.xy, vec2(12.9898, 78.233)))* 43758.5453);
}
//note: remaps v to [0;1] in interval [a;b]
float remap( float a, float b, float v )
{
	return clamp( (v-a) / (b-a), 0.0, 1.0 );
}
//note: quantizes in l levels
float trunc_( float a, float l )
{
	return floor(a*l)/l;
}

float n1rand( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = nrand( n + 0.07*t );
	return nrnd0;
}
float n2rand( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = nrand( n + 0.07*t );
	float nrnd1 = nrand( n + 0.11*t );
	return (nrnd0+nrnd1) / 2.0;
}

float n2rand_faster( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = fract(sin(dot(( n + 0.07*t ).xy, vec2(12.9898, 78.233)))* 43758.5453);

    // Convert uniform distribution into triangle-shaped distribution.
    float orig = nrnd0*2.0-1.0;
    nrnd0 = orig*inversesqrt(abs(orig));
    nrnd0 = max(-1.0,nrnd0); // Nerf the NaN generated by 0*rsqrt(0). Thanks @FioraAeterna!
    nrnd0 = nrnd0-sign(orig)+0.5;
    
    // Result is range [-0.5,1.5] which is
    // useful for actual dithering.
    // convert to [0,1] for histogram.
    return (nrnd0+0.5) * 0.5;
}
float n3rand( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = nrand( n + 0.07*t );
	float nrnd1 = nrand( n + 0.11*t );
	float nrnd2 = nrand( n + 0.13*t );
	return (nrnd0+nrnd1+nrnd2) / 3.0;
}
float n4rand( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = nrand( n + 0.07*t );
	float nrnd1 = nrand( n + 0.11*t );	
	float nrnd2 = nrand( n + 0.13*t );
	float nrnd3 = nrand( n + 0.17*t );
	return (nrnd0+nrnd1+nrnd2+nrnd3) / 4.0;
}
float n4rand_inv( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = nrand( n + 0.07*t );
	float nrnd1 = nrand( n + 0.11*t );	
	float nrnd2 = nrand( n + 0.13*t );
	float nrnd3 = nrand( n + 0.17*t );
    float nrnd4 = nrand( n + 0.19*t );
	float v1 = (nrnd0+nrnd1+nrnd2+nrnd3) / 4.0;
    float v2 = 0.5 * remap( 0.0, 0.5, v1 ) + 0.5;
    float v3 = 0.5 * remap( 0.5, 1.0, v1 );
    return (nrnd4<0.5) ? v2 : v3;
}

float aastep(float threshold, float value) {
  #ifdef GL_OES_standard_derivatives
    float afwidth = length(vec2(dFdx(value), dFdy(value))) * 0.70710678118654757;
    return smoothstep(threshold-afwidth, threshold+afwidth, value);
  #else
    return step(threshold, value);
  #endif  
}
float sdroundrect(vec2 pt, vec2 ext, float rad) {
	vec2 ext2 = ext - vec2(rad,rad);
	vec2 d = abs(pt) - ext2;
	return min(max(d.x,d.y),0.0) + length(max(d,0.0)) - rad;
}

// Scissoring
float scissorMask(vec2 p) {
	vec2 sc = (abs((scissorMat * vec3(p,1.0)).xy) - scissorExt);
	sc = vec2(0.5,0.5) - sc * scissorScale;
	// return min(1.0, sc.x*sc.y);
	return clamp(sc.x,0.0,1.0) * clamp(sc.y,0.0,1.0);
}
#ifdef EDGE_AA
// Stroke - from [0..1] to clipped pyramid, where the slope is 1px.
float strokeMask() {
return smoothstep(0.0, 1.0, (1.0-abs(ftcoord.x*2.0-1.0))*strokeMult) * smoothstep(0.0, 1.0, ftcoord.y);
}
#endif

vec2 getBoxGradient(vec2 texcoord, float e) {
	vec2 BorderInv = clamp(1.0-pow(abs((texcoord*2.0)-1.0), vec2(e)), 0.0, 1.0);
	return BorderInv;
}
vec2 getBoxGradientSmooth(vec2 texcoord) {
	vec2 BorderInv = 0.5 + 0.5*sqrt(4.0*texcoord*(1.0-texcoord));
	return BorderInv;
}
vec2 getBoxGradientNonInverse(vec2 texcoord) {
	vec2 Border = clamp(pow(abs((texcoord*2.0)-1.0), vec2(2.0)), 0.0, 1.0);
	// Border.x = 1;// *= clamp(texcoord.y*1.5-0.4, 0.0, 1.0);
	return Border;
}
float getAntiBandingDither(vec2 pt) {
	float normalizedNoise = n3rand( pt.xy );
	float antiBandingDither = (-0.5+2.0*normalizedNoise)/256.0; // for 8 bit output
	return antiBandingDither;
}
#define COLOR_SHADING 1
vec4 getShadedBox(vec2 pt, vec2 Border, vec4 color, float intens) {
	float fFade = Border.y * Border.y;
	fFade *= Border.x;
	vec3 paletteColor = palette( (1.0)-(Border.y*Border.y*(0.01)+0.18), vec3(0.5),vec3(0.5+intens*1.0),vec3(0.99, 0.95, 0.9),vec3(0.0,0.10,0.20) );
	float globalShadingIntens = 0.2;
	vec4 result = vec4(mix(color.rgb, paletteColor.rgb*intens, globalShadingIntens*fFade), color.a);
	result.rgb+=vec3(getAntiBandingDither(pt));
	return clamp(result, vec4(0.0), vec4(1.0));
}
#define NSVG_SHADER_FILLGRAD 0
#define NSVG_SHADER_FILLIMG 1
#define NSVG_SHADER_SIMPLE 2
#define NSVG_SHADER_IMG 3
#define NSVG_SHADER_BATCHED_TRI_COLORED 4
#define NSVG_SHADER_BATCHED_CIRCLE_COLORED 5
void main(void) {
	float scissor = scissorMask(fpos);
	vec4 result = vec4(0,0,0,1);
	vec2 fragTexCoord = vec2(0);
#ifdef EDGE_AA
	float strokeAlpha = strokeMask();
	if (strokeAlpha < strokeThr) discard;
#else
	float strokeAlpha = 1.0;
#endif
#define SHADE_NANOVG
#ifdef SHADE_NANOVG
	if (type == NSVG_SHADER_FILLGRAD) { // Gradient
		vec2 pt = (paintMat * vec3(fpos,1.0)).xy;
		vec2 texcoord = pt / extent;
		fragTexCoord = texcoord;
		vec4 color = innerCol;
		// Combine alpha
#ifdef COLOR_SHADING
		if (abs(extent.x)+abs(extent.y) > 0) 
		{
			if (texType == 1) {
				float dFeather = 12.0;
				float dRadius = 3.0;
				// float dist = 1.0-clamp((sdroundrect(pt-extent*0.5, extent*0.5, dRadius)+dFeather*0.5)/dFeather, 0.0, 1.0);
				vec2 pixelFromCenter = (pt-extent*0.5);
				vec2 pixelFromBorder = abs(pixelFromCenter) - extent*0.5 + dFeather;
				vec2 borderFade = clamp(pixelFromBorder/dFeather, 0.0, 1.0);
				vec2 invF = vec2(1.0)-borderFade;
				// float dist = length(invF);
				color = getShadedBox(pt, invF, color, -0.2)*1.5;
				// color.r*=1.8;
			} else if (texType == 2) {
				vec2 g = getBoxGradient(texcoord, 2.0);
				float dFeather = 4.0;
				float dRadius = 2.0;
				float dist = 1.0-clamp((sdroundrect(pt-extent*0.5, extent*0.5, dRadius)+dFeather*0.5)/dFeather, 0.0, 1.0);
				color = getShadedBox(pt, vec2(dist)*g, color, 0.3);
			} else if (texType == 3) {
				color = getShadedBox(pt, getBoxGradient(texcoord, 2.0), color, 0.8);
			} else if (texType == 4) {
				color = getShadedBox(pt, getBoxGradientSmooth(texcoord), color, 1.0);
			} else {
				color = getShadedBox(pt, getBoxGradientSmooth(texcoord), color, 0.4);
			}
		}
		// else { color.rgb = vec3(1,0,1); }
#endif
		result = color * strokeAlpha * scissor;
	} else if (type == NSVG_SHADER_FILLIMG) {         // Image
		// Calculate color fron texture
		vec2 pt = (paintMat * vec3(fpos,1.0)).xy / extent;
		fragTexCoord = pt;
#ifdef NANOVG_GL3
		vec4 color = texture(tex, pt);
#else
		vec4 color = texture2D(tex, pt);
#endif
		if (texType == 1) 
			color = vec4(color.xyz*color.w,color.w);
		if (texType == 2) 
			color = vec4(color.x);                // Apply color tint and alpha.
		result = color * innerCol * strokeAlpha * scissor;
#if 0
		result = vec4(0,0,0,1);
		result.y = texture(tex, pt).y;
#endif
	} else if (type == NSVG_SHADER_SIMPLE) {         // Stencil fill
		result = vec4(1,1,1,1);
	} else if (type == NSVG_SHADER_IMG) {         // Textured tris
		fragTexCoord = ftcoord;
#ifdef NANOVG_GL3
		vec4 color = texture(tex, ftcoord);
#else
		vec4 color = texture2D(tex, ftcoord);
#endif
		if (texType == 1) 
			color = vec4(color.xyz*color.w,color.w);
		if (texType == 2) 
			color = vec4(color.x);       
		result = color * innerCol * scissor;
	} else if (type == NSVG_SHADER_BATCHED_TRI_COLORED) {         // colored tri
		fragTexCoord = ftcoord;
		// 0 flat
		// 1 shaded
		// 2 aa vertical lines
		vec4 color = vec4(0.0);
		if (texType == 1) {
			color = getShadedBox(fpos.xy, getBoxGradientSmooth(ftcoord.xy), innerCol, 0.3);
		} else if (texType == 2) {
			float distCenterX = (abs(0.5 - ftcoord.x) * 4.) * 1.0;
			float intens = clamp(1.0 - distCenterX, 0., 1.);
			color = innerCol * intens;
		} else if (texType == 3) {
			float distCenterY = (abs(0.5 - ftcoord.y) * 4.) * 1.0;
			float intens = clamp(1.0 - distCenterY, 0., 1.);
			color = innerCol * intens;
		} else {
			color = innerCol;
		}
		result = color * scissor;
	} else if (type == NSVG_SHADER_BATCHED_CIRCLE_COLORED) {         // circle from rectangle
		fragTexCoord = ftcoord;
		vec2 distCenter = abs((ftcoord-vec2(0.5))*2.0);
		float intens = 1.0f-aastep(0.9, length(distCenter));
		vec2 Border = 0.5 + 0.5*sqrt(4.0*ftcoord*(1.0-ftcoord));
		result = innerCol*scissor;
		result *= Border.y*Border.x*intens;
	}
#endif
#if 0
	// if (result.r < 0 || result.g < 0 || result.b < 0 || result.a < 0) {
	// 	result += vec4(1, 0, 0, 1);
	// }
	result += 0.3*vec4(fragTexCoord.xy, 1.0, 1.0);
#else
#endif
	if (result.a < 1.0/2048.0) 
		discard;
#ifdef NANOVG_GL3
	outColor = result;
#else
	gl_FragColor = result;
#endif
}