#ifdef GL_ES
#if defined(GL_FRAGMENT_PRECISION_HIGH) || defined(NANOVG_GL3)
 precision highp float;
#else
 precision mediump float;
#endif
#endif

// #define NANOVG_GL3

#ifdef NANOVG_GL3
	uniform sampler2D tex;
    uniform vec4 renderInfo;
    uniform vec4 renderColor;
    in vec2 pass_texcoord;
	out vec4 outColor;
#else
	uniform sampler2D tex;
	uniform vec4 renderInfo;
	uniform vec4 renderColor;
	varying vec2 pass_texcoord;
#endif

#define fRenderTime (23.0/7.0)

vec3 palette( in float t, in vec3 a, in vec3 b, in vec3 c, in vec3 d )
{
    return a + b *cos( 6.28318*(c*t+d) );
}

//note: uniformly distributed, normalized rand, [0;1[
float nrand( vec2 n )
{
	return fract(sin(dot(n.xy, vec2(12.9898, 78.233)))* 43758.5453);
}
//note: remaps v to [0;1] in interval [a;b]
float remap( float a, float b, float v )
{
	return clamp( (v-a) / (b-a), 0.0, 1.0 );
}
//note: quantizes in l levels
float trunc_( float a, float l )
{
	return floor(a*l)/l;
}

float n1rand( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = nrand( n + 0.07*t );
	return nrnd0;
}
float n2rand( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = nrand( n + 0.07*t );
	float nrnd1 = nrand( n + 0.11*t );
	return (nrnd0+nrnd1) / 2.0;
}

float n2rand_faster( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = fract(sin(dot(( n + 0.07*t ).xy, vec2(12.9898, 78.233)))* 43758.5453);

    // Convert uniform distribution into triangle-shaped distribution.
    float orig = nrnd0*2.0-1.0;
    nrnd0 = orig*inversesqrt(abs(orig));
    nrnd0 = max(-1.0,nrnd0); // Nerf the NaN generated by 0*rsqrt(0). Thanks @FioraAeterna!
    nrnd0 = nrnd0-sign(orig)+0.5;
    
    // Result is range [-0.5,1.5] which is
    // useful for actual dithering.
    // convert to [0,1] for histogram.
    return (nrnd0+0.5) * 0.5;
}
float n3rand( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = nrand( n + 0.07*t );
	float nrnd1 = nrand( n + 0.11*t );
	float nrnd2 = nrand( n + 0.13*t );
	return (nrnd0+nrnd1+nrnd2) / 3.0;
}
float n4rand( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = nrand( n + 0.07*t );
	float nrnd1 = nrand( n + 0.11*t );	
	float nrnd2 = nrand( n + 0.13*t );
	float nrnd3 = nrand( n + 0.17*t );
	return (nrnd0+nrnd1+nrnd2+nrnd3) / 4.0;
}

float aastep(float threshold, float value) {
  #ifdef GL_OES_standard_derivatives
    float afwidth = length(vec2(dFdx(value), dFdy(value))) * 0.70710678118654757;
    return smoothstep(threshold-afwidth, threshold+afwidth, value);
  #else
    return step(threshold, value);
  #endif  
}

const float texW = 512.0;
const float oneOverTexSize = 1.0/texW;

void main(void) {
   		vec4 result = vec4(0,0,0,1);
#ifdef NANOVG_GL3
		vec4 texSample = texture(tex, pass_texcoord);
#else
		vec4 texSample = texture2D(tex, pass_texcoord);
#endif
#if 1
        float pixX = floor((pass_texcoord.x) * renderInfo.z) + floor(texW-renderInfo.z);
        vec2 samplePos = vec2(pixX+0.5, renderInfo.y+0.5);
		float sampleVal = texture2D(tex, samplePos * oneOverTexSize).r;
        // float ssteps = 2.0;
        // float stepRange = 0.5;
        // float sampleVal2 = 0.0;
        // for (float i = 0.0; i < ssteps; i++) {

		//     sampleVal2 += texture2D(tex, vec2(pass_texcoord.x-((i+1.0)*oneOverTexSize)*stepRange, (renderInfo.y+0.5) * oneOverTexSize * vec2(r, 1.0))).r;
        //     sampleVal2 += texture2D(tex, vec2(pass_texcoord.x+((i+1.0)*oneOverTexSize)*stepRange, (renderInfo.y+0.5) * oneOverTexSize * vec2(r, 1.0))).r;
        // }
        // sampleVal2 /= (ssteps*2.0);
        float d = sampleVal-pass_texcoord.y;
        float f2 = 0.5*fwidth(d);
        float f3 = smoothstep(-f2, f2, d);
		float intens = aastep(0.0, sampleVal-pass_texcoord.y); //aastep(sampleVal, pass_texcoord.y);
        // intens *= 0.5+0.5*sampleVal;
        result = vec4(vec3(renderColor.rgb * vec3(f3)), 1.0);
#endif
#if 0
        float pixX = floor(pass_texcoord.x * renderInfo.z) + floor(texW-renderInfo.z);
        vec2 samplePos = vec2(pixX+0.5, renderInfo.y+0.5);
		float sampleVal = texture2D(tex, samplePos * oneOverTexSize).r;
		float intens = aastep(0.0, sampleVal-pass_texcoord.y); //aastep(sampleVal, pass_texcoord.y);
        intens *= 0.5+0.5*sampleVal;
        result = vec4(vec3(renderColor.rgb * vec3(intens)), 1);
#endif
#if 0
        //nice looking
        float pixX = floor(pass_texcoord.x * renderInfo.z) + floor(texW-renderInfo.z);
        vec2 samplePos = vec2(pixX+0.5, renderInfo.y+0.5);
		float sampleVal = texture2D(tex, samplePos * oneOverTexSize).r;
		float sampleVal2 = texture2D(tex, samplePos * oneOverTexSize - vec2(oneOverTexSize, 0)).r;
		float sampleVal3 = texture2D(tex, samplePos * oneOverTexSize + vec2(oneOverTexSize, 0)).r;
        float neighboursIntens = (sampleVal2+sampleVal3) * 0.5;
		float intens = 1.0-smoothstep(0.0, sampleVal, pass_texcoord.y); //aastep(sampleVal, pass_texcoord.y);
        intens*=intens;
        intens*=intens;
        intens*=0.8+neighboursIntens;
		intens *= 1.0-aastep(sampleVal, pass_texcoord.y);
        intens *= 0.5+0.5*sampleVal;
        result = vec4(vec3(renderColor.rgb * vec3(intens)), 1);
#endif

#if 0
        float nSteps = renderInfo.z/4.0;
        float xOffsetNext = abs(round(pass_texcoord.x * nSteps)-(pass_texcoord.x * nSteps))*nSteps;
        float pixX = floor(pass_texcoord.x * nSteps) + floor(texW-nSteps);
        vec2 samplePos = vec2(pixX+0.5, renderInfo.y+0.5);
		float sampleVal = texture2D(tex, samplePos * oneOverTexSize).r;
		float intens = aastep(0.0, sampleVal-pass_texcoord.y);
		float w = 0.5*fwidth(xOffsetNext); 
        vec4 colShape = vec4(renderColor);
		intens *= smoothstep(-w,w, xOffsetNext-(nSteps/4.0));
        result = mix(vec4(0), colShape, intens);

#endif
		// if (result.a < 1.0/1024.0) 
		// 	discard;

#ifdef NANOVG_GL3
        outColor = result;
#else
        gl_FragColor = result;
#endif
}