#define NANOVG_GL3

#ifdef NANOVG_GL3
	uniform sampler2D tex0;
    uniform vec4 u_renderInfo;
    uniform vec4 u_renderColor;
    uniform vec2 u_viewport;
    uniform float u_time;
    in vec2 pass_texcoord;
    in vec4 pass_position;
	out vec4 outColor;
#else
	uniform sampler2D tex0;
	uniform vec4 u_renderInfo;
	uniform vec4 u_renderColor;
	varying vec2 pass_texcoord;
#endif

const vec2 INV_TEXSIZE = vec2(1.0/TEXTURE_WIDTH, 1.0/TEXTURE_HEIGHT);

#define fRenderTime (23.0/7.0)

vec3 palette( in float t, in vec3 a, in vec3 b, in vec3 c, in vec3 d )
{
    return a + b *cos( 6.28318*(c*t+d) );
}

//note: uniformly distributed, normalized rand, [0;1[
float nrand( vec2 n )
{
	return fract(sin(dot(n.xy, vec2(12.9898, 78.233)))* 43758.5453);
}
//note: remaps v to [0;1] in interval [a;b]
float remap( float a, float b, float v )
{
	return clamp( (v-a) / (b-a), 0.0, 1.0 );
}
//note: quantizes in l levels
float trunc_( float a, float l )
{
	return floor(a*l)/l;
}

float n1rand( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = nrand( n + 0.07*t );
	return nrnd0;
}
float n2rand( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = nrand( n + 0.07*t );
	float nrnd1 = nrand( n + 0.11*t );
	return (nrnd0+nrnd1) / 2.0;
}

float n2rand_faster( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = fract(sin(dot(( n + 0.07*t ).xy, vec2(12.9898, 78.233)))* 43758.5453);

    // Convert uniform distribution into triangle-shaped distribution.
    float orig = nrnd0*2.0-1.0;
    nrnd0 = orig*inversesqrt(abs(orig));
    nrnd0 = max(-1.0,nrnd0); // Nerf the NaN generated by 0*rsqrt(0). Thanks @FioraAeterna!
    nrnd0 = nrnd0-sign(orig)+0.5;
    
    // Result is range [-0.5,1.5] which is
    // useful for actual dithering.
    // convert to [0,1] for histogram.
    return (nrnd0+0.5) * 0.5;
}
float n3rand( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = nrand( n + 0.07*t );
	float nrnd1 = nrand( n + 0.11*t );
	float nrnd2 = nrand( n + 0.13*t );
	return (nrnd0+nrnd1+nrnd2) / 3.0;
}
float n4rand( vec2 n )
{
	float t = fract( fRenderTime );
	float nrnd0 = nrand( n + 0.07*t );
	float nrnd1 = nrand( n + 0.11*t );	
	float nrnd2 = nrand( n + 0.13*t );
	float nrnd3 = nrand( n + 0.17*t );
	return (nrnd0+nrnd1+nrnd2+nrnd3) / 4.0;
}

float aastep(float threshold, float value) {
  #ifdef GL_OES_standard_derivatives
    float afwidth = length(vec2(dFdx(value), dFdy(value))) * 0.70710678118654757;
    return smoothstep(threshold-afwidth, threshold+afwidth, value);
  #else
    return step(threshold, value);
  #endif  
}


void main(void) {
   		vec4 result = vec4(0,0,0,1);
#if 1
        #define CHANNEL u_renderInfo.y
        #define WIDTH_GRAPH u_renderInfo.z
        #define HEIGHT_GRAPH u_renderInfo.w
        // float pixX = (pass_texcoord.x * WIDTH_GRAPH) + (TEXTURE_WIDTH-WIDTH_GRAPH);
        float pixX = (1.0-pass_texcoord.x)*WIDTH_GRAPH;

        ivec2 texelPos = ivec2(TEXTURE_WIDTH - 1 - floor(pixX), int(CHANNEL));
		float sampleVal = texelFetch(tex0, texelPos, 0).r;
        int ssteps = 0;
        // float stepRange = 0.5;
        // float sampleVal2 = 0.0;
        for (float i = 0; i < ssteps; i++) {
		    sampleVal += texelFetch(tex0, texelPos + ivec2(i, 0), 0).r;
		    sampleVal += texelFetch(tex0, texelPos - ivec2(i, 0), 0).r;
        }
        sampleVal /= float(ssteps*2 + 1);
        // sampleVal = float(texelPos.x % 8 == 0);
        float d = max(0, pow(max(0.0, sampleVal - pass_texcoord.y), .25));
        // float f2 = 0.5*dFdx(pass_texcoord.x*TEXTURE_WIDTH);
        // float f3 = smoothstep(-f2, f2, d);
            
        // float a=2.*WIDTH_GRAPH/TEXTURE_WIDTH;
        // float b=smoothstep(a,a,fwidth(d));
		// float intens = aastep(0.0, sampleVal - pass_texcoord.y); //aastep(sampleVal, pass_texcoord.y);
        // intens *= 0.5+0.5*sampleVal;
        // result = vec4(vec3(sampleVal), 1.0);
        float fPixPos = (pass_position.x * 0.5 + 0.5) * u_viewport.x;
        int stride = int(floor(u_time/200.0))%16 + 1;
        result = vec4(u_renderColor.rgb * d, 1.0);
#endif
#if 0
        float pixX = floor(pass_texcoord.x * u_renderInfo.z) + floor(TEXTURE_WIDTH-u_renderInfo.z);
        vec2 samplePos = vec2(pixX+0.5, u_renderInfo.y+0.5);
		float sampleVal = texture2D(tex0, samplePos * INV_TEXSIZE).r;
		float intens = aastep(0.0, sampleVal-pass_texcoord.y); //aastep(sampleVal, pass_texcoord.y);
        intens *= 0.5+0.5*sampleVal;
        result = vec4(vec3(u_renderColor.rgb * vec3(intens)), 1);
#endif
#if 0
        //nice looking
        float pixX = floor(pass_texcoord.x * u_renderInfo.z) + floor(TEXTURE_WIDTH-u_renderInfo.z);
        vec2 samplePos = vec2(pixX+0.5, u_renderInfo.y+0.5);
		float sampleVal = texture2D(tex0, samplePos * INV_TEXSIZE).r;
		float sampleVal2 = texture2D(tex0, samplePos * INV_TEXSIZE - vec2(INV_TEXSIZE, 0)).r;
		float sampleVal3 = texture2D(tex0, samplePos * INV_TEXSIZE + vec2(INV_TEXSIZE, 0)).r;
        float neighboursIntens = (sampleVal2+sampleVal3) * 0.5;
		float intens = 1.0-smoothstep(0.0, sampleVal, pass_texcoord.y); //aastep(sampleVal, pass_texcoord.y);
        intens*=intens;
        intens*=intens;
        intens*=0.8+neighboursIntens;
		intens *= 1.0-aastep(sampleVal, pass_texcoord.y);
        intens *= 0.5+0.5*sampleVal;
        result = vec4(vec3(u_renderColor.rgb * vec3(intens)), 1);
#endif

#if 0
        float nSteps = u_renderInfo.z/4.0;
        float xOffsetNext = abs(round(pass_texcoord.x * nSteps)-(pass_texcoord.x * nSteps))*nSteps;
        float pixX = floor(pass_texcoord.x * nSteps) + floor(TEXTURE_WIDTH-nSteps);
        vec2 samplePos = vec2(pixX+0.5, u_renderInfo.y+0.5);
		float sampleVal = texture2D(tex0, samplePos * INV_TEXSIZE).r;
		float intens = aastep(0.0, sampleVal-pass_texcoord.y);
		float w = 0.5*fwidth(xOffsetNext); 
        vec4 colShape = vec4(u_renderColor);
		intens *= smoothstep(-w,w, xOffsetNext-(nSteps/4.0));
        result = mix(vec4(0), colShape, intens);

#endif
		// if (result.a < 1.0/1024.0) 
		// 	discard;

#ifdef NANOVG_GL3
        // outColor = vec4(vec3(1), float(result.r!=0))
        // outColor = vec4(result.rgb, 1.0);
        outColor = vec4(result.rgb + u_renderColor.bgr*(1.0-pass_texcoord.y)*0.2, 1.0);
#else
        gl_FragColor = result;
#endif
}