get_cmake_property(_varNames VARIABLES)
list (REMOVE_DUPLICATES _varNames)
list (SORT _varNames)
foreach (_varName ${_varNames})
  if (_varName MATCHES "CMAKE_C([X][X])?_FLAGS.*_INIT$")
    if (MSVC)
      # remove default warning level from CMAKE_CXX_FLAGS_INIT
      string (REGEX REPLACE "/W[0-4]" "" ${_varName} "${${_varName}}")
      string (REGEX REPLACE "/O2" "/O2 /fp:fast" ${_varName} "${${_varName}}")
      string (REGEX REPLACE "/Ob1" "/Ob2" ${_varName} "${${_varName}}")
      string (REGEX REPLACE "/Ob2" "/Ob3 /Gy" ${_varName} "${${_varName}}")
    else()
      string (REGEX REPLACE "-O2" "-Ofast -ffast-math" ${_varName} "${${_varName}}")
      string (REGEX REPLACE "-O3" "-Ofast -ffast-math" ${_varName} "${${_varName}}")
    endif()
  endif()
endforeach()
if (MSVC)
  set(CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT " /INCREMENTAL:NO /OPT:REF /OPT:ICF")
  set(CMAKE_SHARED_LINKER_FLAGS_RELEASE_INIT " /INCREMENTAL:NO /OPT:REF /OPT:ICF")
  set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO_INIT " /debug /INCREMENTAL:NO /OPT:REF /OPT:ICF")
  set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO_INIT " /debug /INCREMENTAL:NO /OPT:REF /OPT:ICF")
endif()
