#pragma once
#define CURSOR_DEFAULT 0
#define CURSOR_CLIP_SIZE_RIGHT 1
#define CURSOR_CLIP_SIZE_LEFT 2
#define CURSOR_RESIZE_V 3
#define CURSOR_RESIZE_H 4
#define CURSOR_DUPLICATE 5
#define CURSOR_ZOOM 6
#define MOUSE_BUTTON_LEFT 0
#define MOUSE_BUTTON_RIGHT 1
#define MOUSE_BUTTON_MIDDLE 2
#define MOUSE_BUTTON_4 3
#define MOUSE_BUTTON_5 4
#define MOUSE_BUTTON_MAX 8
#define MOUSEINPUT_CURSOR_NORMAL 0x00034001
#define MOUSEINPUT_CURSOR_HIDDEN 0x00034002
#define MOUSEINPUT_CURSOR_DISABLED 0x00034003
